version: "3.5"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    restart: unless-stopped
    container_name: elasticsearch
    environment:
      - cluster.name=elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    build:
      context: ./kibana
    restart: unless-stopped
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - esnet

  logstash:
    build:
      context: ./logstash
    restart: unless-stopped
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xms536m -Xmx536m"
    depends_on:
      - elasticsearch
    volumes:
      - logstash_data:/usr/share/logstash/data
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/script:/usr/share/logstash/script
    networks:
      - esnet

  nginx:
    build: ./nginx
    restart: unless-stopped
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/src/frontend:/usr/share/nginx/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
    name: icis_esdata
  logstash_data:
    driver: local
    name: icis_lsdata
  # nginx_conf:
  #   driver: local

networks:
  esnet:
    name: icis
